import 'server-only'
import { getDocBySlug, searchDocsFull } from '@/lib/docs-store'
import type { SearchHit } from '@/lib/docs-data'

/**
 * Retrieval layer for the assistant. Questions are matched against the full
 * indexed corpus; each hit exposes its stored body so answers stay grounded in
 * the official sources.
 */

export function hasLlmProvider() {
  return Boolean(process.env.OPENAI_API_KEY || process.env.AI_GATEWAY_API_KEY)
}

export function retrieve(question: string, limit = 6): SearchHit[] {
  return searchDocsFull(question, limit)
}

export function buildContext(hits: SearchHit[]): string {
  return hits
    .map((hit, index) => {
      const doc = getDocBySlug(hit.doc.slug)
      const body = (doc?.content ?? '').trim().slice(0, 3500)
      return `SOURCE ${index + 1}: ${hit.doc.title}
Section: ${hit.doc.section}
URL: ${hit.doc.sourceUrl}
${hit.snippet ?? hit.doc.excerpt}
${body ? `\n${body}` : ''}`
    })
    .join('\n\n---\n\n')
}

export type Source = {
  title: string
  slug: string
  section: string
  category: string
  sourceUrl: string
  excerpt: string
  relevance: number
}

export function sourcesFrom(hits: SearchHit[]): Source[] {
  return hits.map((hit) => ({
    title: hit.doc.title,
    slug: hit.doc.slug,
    section: hit.doc.section,
    category: hit.doc.category,
    sourceUrl: hit.doc.sourceUrl,
    excerpt: hit.snippet ?? hit.doc.excerpt,
    relevance: Math.round(hit.score * 100) / 100,
  }))
}

export function extractiveAnswer(question: string, hits: SearchHit[]): string[] {
  if (!hits.length) {
    return [
      `I could not find indexed documentation that directly answers “${question}”.`,
      '',
      'Try rephrasing, or open the official v0 documentation to search the full corpus: https://v0.app/docs',
    ]
  }

  const lines: string[] = []
  lines.push(
    `Based on the indexed v0 documentation, here is what the corpus says about “${question}”.`,
  )
  lines.push('')
  lines.push(
    '> This answer was generated by the application from the indexed sources. The authoritative text lives in the official v0 docs linked per source.',
  )

  hits.forEach((hit, index) => {
    lines.push('')
    lines.push(`### ${index + 1}. ${hit.doc.title}  ·  ${hit.doc.section}`)
    if (hit.snippet) lines.push('', hit.snippet)
    lines.push('', `Source: ${hit.doc.sourceUrl}`)
  })

  lines.push('')
  lines.push(
    `Retrieved ${hits.length} indexed document${hits.length === 1 ? '' : 's'}. Open the sources above for the canonical details.`,
  )
  return lines
}
