import manifest from '@/data/docs-manifest.json'

/**
 * Canonical documentation knowledge base, loaded from `data/docs-manifest.json`
 * (generated by `scripts/ingest-docs.mjs` from the official v0 docs).
 *
 * This module exposes lightweight document summaries (no full content) so it is
 * safe to import from client components. Server pages and API routes that need
 * full content should use `@/lib/docs-store`.
 */

export type DocSummary = {
  id: string
  slug: string
  title: string
  section: string
  category: string
  type: string
  description: string
  topics: string[]
  related: string[]
  requires: string[]
  headings: string[]
  excerpt: string
  snippets: Pick<{ language: string; code: string }, 'language' | 'code'>[]
  sourceUrl: string
  lastUpdated?: string
}

export type SearchHit = {
  doc: DocSummary
  score: number
  reasons: string[]
  snippet?: string
}

type RawDoc = Omit<DocSummary, 'snippets'> & {
  snippets: { language: string; code: string }[]
  content: string
}

const raws = (manifest.docs as RawDoc[]) ?? []

export const docs: DocSummary[] = raws.map(({ content: _content, ...rest }) => rest)

export const generatedAt: string = manifest.generatedAt ?? ''
export const crawlReport: Record<string, unknown> = manifest.report ?? {}

export const sections: string[] = [...new Set(docs.map((doc) => doc.section))]
export const categories: string[] = [...new Set(docs.map((doc) => doc.category))]
export const topics: string[] = [...new Set(docs.flatMap((doc) => doc.topics))].sort()

const slugIndex = new Map(docs.map((doc) => [doc.slug.toLowerCase(), doc]))

export function getDoc(slug: string): DocSummary | undefined {
  if (!slug) return undefined
  const direct = slugIndex.get(slug.toLowerCase())
  if (direct) return direct
  return docs.find(
    (doc) =>
      doc.id.toLowerCase() === `docs-${slug}`.toLowerCase() ||
      doc.id.toLowerCase() === slug.toLowerCase(),
  )
}

export function getSectionDocs(section: string): DocSummary[] {
  return docs.filter((doc) => doc.section === section)
}

export function getCategoryDocs(category: string): DocSummary[] {
  return docs.filter((doc) => doc.category === category)
}

export function getDocsForTopic(topic: string): DocSummary[] {
  return docs.filter((doc) => doc.topics.some((t) => t.toLowerCase() === topic.toLowerCase()))
}

export function prevNext(doc: DocSummary): { prev?: DocSummary; next?: DocSummary } {
  const sectionDocs = getSectionDocs(doc.section)
  const index = sectionDocs.findIndex((d) => d.id === doc.id)
  return {
    prev: index > 0 ? sectionDocs[index - 1] : undefined,
    next: index >= 0 && index < sectionDocs.length - 1 ? sectionDocs[index + 1] : undefined,
  }
}

export function relatedDocs(doc: DocSummary): DocSummary[] {
  const seen = new Set<string>()
  const result: DocSummary[] = []
  const consider = (slug?: string) => {
    if (!slug) return
    const match = getDoc(slug)
    if (match && match.id !== doc.id && !seen.has(match.id)) {
      seen.add(match.id)
      result.push(match)
    }
  }
  doc.related.forEach(consider)
  doc.requires.forEach(consider)
  docs
    .filter((d) => d !== doc && d.topics.some((t) => doc.topics.includes(t)))
    .forEach((d) => consider(d.slug))
  return result.slice(0, 6)
}

function tokenize(value: string): string[] {
  return value
    .toLowerCase()
    .split(/[^a-z0-9+./#-]+/)
    .filter((token) => token.length > 1)
}

function excerptAround(content: string, term: string, radius = 180): string {
  const index = content.toLowerCase().indexOf(term.toLowerCase())
  if (index === -1) return content.slice(0, radius * 2)
  const start = Math.max(0, index - radius)
  const end = Math.min(content.length, index + term.length + radius)
  const before = start > 0 ? '…' : ''
  const after = end < content.length ? '…' : ''
  return `${before}${content.slice(start, end).replace(/\s+/g, ' ')}${after}`
}

export function searchDocs(query: string, limit = 20): SearchHit[] {
  const normalized = query.trim()
  if (!normalized) return []
  const queryTokens = tokenize(normalized)
  if (!queryTokens.length) return []

  const hits: SearchHit[] = docs
    .map((doc) => {
      let score = 0
      const reasons: string[] = []
      const title = doc.title.toLowerCase()
      const description = doc.description.toLowerCase()
      const section = doc.section.toLowerCase()
      const category = doc.category.toLowerCase()
      const headings = doc.headings.join('  ').toLowerCase()
      const topicsJoined = doc.topics.join(' ').toLowerCase()
      const all = `${title} ${description} ${headings} ${topicsJoined} ${section} ${category} ${doc.slug}`

      for (const token of queryTokens) {
        if (title.includes(token)) score += 6
        if (headings.includes(token)) score += 3
        if (topicsJoined.includes(token)) score += 3
        if (description.includes(token)) score += 3
        if (doc.slug.includes(token)) score += 2
        if (category.includes(token) || section.includes(token)) score += 1.5
        if (all.includes(token)) score += 1
      }
      if (!score) return undefined

      const exactPhrase = normalized.toLowerCase()
      if (title.includes(exactPhrase)) {
        score += 12
        reasons.push('Title match')
      } else if (description.includes(exactPhrase)) {
        reasons.push('Description match')
      } else if (headings.includes(exactPhrase)) {
        score += 4
        reasons.push('Heading match')
      } else if (topicsJoined.includes(exactPhrase)) {
        reasons.push('Topic match')
      } else {
        reasons.push('Keyword match')
      }
      return { doc, score, reasons: reasons.length ? reasons : ['Keyword match'] }
    })
    .filter((hit): hit is SearchHit => Boolean(hit))

  return hits.sort((a, b) => b.score - a.score).slice(0, limit)
}

export function searchDocsFull(
  query: string,
  contentGetter: (slug: string) => string,
  limit = 12,
): SearchHit[] {
  const hits = searchDocs(query, Math.max(limit * 3, 30))
  const normalized = query.trim().toLowerCase()
  const primaryTerm = tokenize(normalized)[0]
  const contentHits: SearchHit[] = []
  const seen = new Set<string>()

  for (const hit of hits) {
    const content = contentGetter(hit.doc.slug) ?? ''
    const lower = content.toLowerCase()
    const contentScore = primaryTerm && lower.includes(primaryTerm) ? 2 : 0
    if (contentScore) {
      contentHits.push({
        ...hit,
        score: hit.score + contentScore,
        snippet: excerptAround(content, primaryTerm),
      })
    } else {
      contentHits.push({ ...hit, snippet: hit.doc.excerpt })
    }
    seen.add(hit.doc.id)
  }

  return contentHits.sort((a, b) => b.score - a.score).slice(0, limit)
}

export function coverageStats() {
  const total = docs.length
  const bySection = Object.fromEntries(
    sections.map((section) => [section, getSectionDocs(section).length]),
  )
  const withCode = docs.filter((doc) => doc.snippets.length > 0).length
  const withApi = docs.filter((doc) => doc.section === 'API Reference').length
  const integrations = docs.filter((doc) => doc.section === 'Integrations').length
  const withTopics = docs.filter((doc) => doc.topics.length > 0).length
  const withRelated = docs.filter((doc) => doc.related.length > 0 || doc.requires.length > 0).length
  const topicsCount = topics.length
  return {
    total,
    bySection,
    withCode,
    withApi,
    integrations,
    withTopics,
    withRelated,
    topicsCount,
    generatedAt,
    crawled: crawlReport,
  }
}
