import Link from 'next/link'
import { coverageStats } from '@/lib/docs-data'
import { CrawlTool } from '@/components/admin/crawl-tool'

export default function AdminPage() {
  const stats = coverageStats()
  return (
    <main className="mx-auto min-h-screen max-w-5xl px-6 py-12">
      <p className="text-sm text-muted-foreground">Application administration</p>
      <h1 className="mt-3 text-4xl font-semibold tracking-tight">Admin</h1>
      <p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">
        Inspect the indexed knowledge base and re-ingest individual pages. The canonical corpus is
        generated by <code className="rounded bg-muted px-1.5 py-0.5">scripts/ingest-docs.mjs</code>{' '}
        and shipped as static data; production refreshes require a rebuild.
      </p>

      <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <div className="rounded-2xl border border-border bg-card p-5">
          <p className="text-sm text-muted-foreground">Indexed pages</p>
          <p className="mt-2 text-3xl font-semibold">{stats.total}</p>
        </div>
        <div className="rounded-2xl border border-border bg-card p-5">
          <p className="text-sm text-muted-foreground">API reference</p>
          <p className="mt-2 text-3xl font-semibold">{stats.withApi}</p>
        </div>
        <div className="rounded-2xl border border-border bg-card p-5">
          <p className="text-sm text-muted-foreground">Integrations</p>
          <p className="mt-2 text-3xl font-semibold">{stats.integrations}</p>
        </div>
        <div className="rounded-2xl border border-border bg-card p-5">
          <p className="text-sm text-muted-foreground">Pages with code</p>
          <p className="mt-2 text-3xl font-semibold">{stats.withCode}</p>
        </div>
        <div className="rounded-2xl border border-border bg-card p-5">
          <p className="text-sm text-muted-foreground">Unique topics</p>
          <p className="mt-2 text-3xl font-semibold">{stats.topicsCount}</p>
        </div>
        <div className="rounded-2xl border border-border bg-card p-5">
          <p className="text-sm text-muted-foreground">Manifest generated</p>
          <p className="mt-2 text-sm font-medium text-muted-foreground">
            {stats.generatedAt ? new Date(stats.generatedAt).toUTCString() : '—'}
          </p>
        </div>
      </div>

      <div className="mt-6 grid gap-6 lg:grid-cols-2">
        <CrawlTool />
        <div className="rounded-2xl border border-border bg-card p-6">
          <h2 className="font-medium">Coverage report</h2>
          <p className="mt-2 text-sm text-muted-foreground">
            The source-attributed report over the indexed corpus.
          </p>
          <Link
            href="/admin/coverage"
            className="mt-5 inline-flex items-center rounded-lg bg-foreground px-4 py-2 text-sm font-medium text-background hover:opacity-90"
          >
            View coverage →
          </Link>
          <div className="mt-6 space-y-2 text-sm">
            {Object.entries(stats.bySection).map(([section, count]) => (
              <div
                key={section}
                className="flex items-center justify-between text-muted-foreground"
              >
                <span>{section}</span>
                <span className="font-medium text-foreground">{count as number}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </main>
  )
}
